name: Job
on:
    workflow_dispatch:
    schedule:
        - cron: '*/10 * * * *'
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
                  run_install: true
            - run: node run.js
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
